apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledj-deployment
  labels:
    app: ledj-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledj-demo
  template:
    metadata:
      name: ledj-deployment
      labels:
        app: ledj-demo
    spec:
      containers:
        - name: ledj-demo
          image: ledj1996/demo:new
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
      